### ISSUE TITLE
Lorikeet name on PyPI

### ISSUE THREAD

**Issue by adambrenecki** [SciTools-incubator/lorikeet#1]
Hi,

I've started building a project at work which I was later given permission to open source, which I've also called Lorikeet ([source](https://gitlab.com/abre/lorikeet), [documentation](https://lorikeet.readthedocs.io/en/latest/)).

We're now at the point where we're thinking about starting to publish pre-release distributions to PyPI, but rather foolishly I didn't check to see if the name 'lorikeet' was taken when I first started work on it. As far as I can tell it's taken by this project, but there's no releases or metadata uploaded on PyPI so it's hard to tell.

If there's no plans to continue work on this project, is there any chance we could have use of the 'lorikeet' name on PyPI? As there's currently no releases uploaded, this shouldn't cause any problems for anyone, because nobody will have been able to add a dependency on the existing 'lorikeet' entry and successfully install their package.

Of course, if this isn't possible we can work around it, but if it is possible that would be super amazing (especially since I've grown rather fond of the name; it came about because the code was originally written for the online store of a wine brand, and I'd just come across [this Australian Geographic article about red-collared lorikeets getting drunk from eating fermented fruit](http://www.australiangeographic.com.au/topics/wildlife/2011/10/drunk-birds-inebriation-in-the-wild/)).

Thanks, Adam

**Comment by pelson** [comment]
@marqh - not sure how you feel about this? I notice you do have some code in https://github.com/marqh/lorikeet, but nothing pushed here / no PRs etc.

It's clear that the name *is* super awesome, but I'm keen to avoid being name squatters. Unless we have some concrete plans to move the project forward, I would be sympathetic to transferring the name over to @adambrenecki.

@adambrenecki - thank for asking the question.

**Comment by marqh** [comment]
@adambrenecki apologies that i missed your initial post

we've not made any progress with Lorikeet so we can relinquish the pypi name to you

I guess I need to give it up then you take it over, or can I make you an admin and switch that way?
any thoughts?
what is your pypi userid?
does it still matter?

**Comment by adambrenecki** [comment]
Thanks!

My PyPI user ID is `adambrenecki`. If you make me an admin of the package, I can probably figure it out from there.

**Comment by marqh** [comment]
@adambrenecki you should have ownership of this on pypi now

mark

**Comment by pelson** [comment]
Thanks @marqh.

@adambrenecki - good luck with the lorikeet package! 

🎉
